package eu.apenet.persistence.vo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

// Generated 19-ene-2011 16:06:41 by Hibernate Tools 3.2.4.GA
/**
 * AlternativeName generated by hbm2java
 */
@Entity
@Table(name = "ai_alternative_name")
public class AiAlternativeName implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 6146971098640916650L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int aiAnId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lng_id", foreignKey = @ForeignKey(name = "lang_lng_id_fkey"))
    private Lang lang;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ai_id", foreignKey = @ForeignKey(name = "archival_institution_ai_id_fkey"))
    private ArchivalInstitution archivalInstitution;
    @Column(name = "ai_a_name")
    private String AiAName;
    @Column(name = "primary_name")
    private Boolean primaryName;

    public AiAlternativeName() {
    }

    public AiAlternativeName(int aiAnId, Lang lang,
            ArchivalInstitution archivalInstitution, String AiAName) {
        this.aiAnId = aiAnId;
        this.lang = lang;
        this.archivalInstitution = archivalInstitution;
        this.AiAName = AiAName;
    }

    public int getAiAnId() {
        return this.aiAnId;
    }

    public void setAiAnId(int aiAnId) {
        this.aiAnId = aiAnId;
    }

    public Lang getLang() {
        return this.lang;
    }

    public void setLang(Lang lang) {
        this.lang = lang;
    }

    public ArchivalInstitution getArchivalInstitution() {
        return this.archivalInstitution;
    }

    public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
        this.archivalInstitution = archivalInstitution;
    }

    public String getAiAName() {
        return this.AiAName;
    }

    public void setAiAName(String AiAName) {
        this.AiAName = AiAName;
    }

    public Boolean getPrimaryName() {
        return primaryName;
    }

    public void setPrimaryName(Boolean primaryName) {
        this.primaryName = primaryName;
    }

}
