package eu.apenet.persistence.vo;

// Generated 19-ene-2011 16:06:41 by Hibernate Tools 3.2.4.GA

/**
 * AlternativeName generated by hbm2java
 */
public class AiAlternativeName implements java.io.Serializable {

	private int aiAnId;
	private Lang lang;
	private ArchivalInstitution archivalInstitution;
	private String AiAName;
	private Boolean primaryName;

	public AiAlternativeName() {
	}

	public AiAlternativeName(int aiAnId, Lang lang,
			ArchivalInstitution archivalInstitution, String AiAName) {
		this.aiAnId = aiAnId;
		this.lang = lang;
		this.archivalInstitution = archivalInstitution;
		this.AiAName = AiAName;
	}

	public int getAiAnId() {
		return this.aiAnId;
	}

	public void setAiAnId(int aiAnId) {
		this.aiAnId = aiAnId;
	}

	public Lang getLang() {
		return this.lang;
	}

	public void setLang(Lang lang) {
		this.lang = lang;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return this.archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public String getAiAName() {
		return this.AiAName;
	}

	public void setAiAName(String AiAName) {
		this.AiAName = AiAName;
	}

	public Boolean getPrimaryName() {
		return primaryName;
	}

	public void setPrimaryName(Boolean primaryName) {
		this.primaryName = primaryName;
	}

}
