package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchivalInstitutionOaiPmh generated by hbm2java
 */
@Entity
@Table(name = "archival_institution_oai_pmh")
public class ArchivalInstitutionOaiPmh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3915319770716474956L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private Integer aioId;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="last_harvesting")
	private Date lastHarvesting;

	@Column(name="oai_pmh_id")
	private Integer oaiPmhId;

	@Column(name="oai_pmh_url")
	private String oaiPmhUrl;

	//bi-directional many-to-one association to ArchivalInstitution
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ai_id")
	private ArchivalInstitution archivalInstitution;

	public ArchivalInstitutionOaiPmh() {
	}

	public ArchivalInstitutionOaiPmh(int aioId,
			ArchivalInstitution archivalInstitution, int oaiPmhId,
			String oaiPmhUrl) {
		this.aioId = aioId;
		this.archivalInstitution = archivalInstitution;
		this.oaiPmhId = oaiPmhId;
		this.oaiPmhUrl = oaiPmhUrl;
	}

	public ArchivalInstitutionOaiPmh(int aioId,
			ArchivalInstitution archivalInstitution, int oaiPmhId,
			String oaiPmhUrl, Date lastHarvesting) {
		this.aioId = aioId;
		this.archivalInstitution = archivalInstitution;
		this.oaiPmhId = oaiPmhId;
		this.oaiPmhUrl = oaiPmhUrl;
		this.lastHarvesting = lastHarvesting;
	}

	public int getAioId() {
		return this.aioId;
	}

	public void setAioId(int aioId) {
		this.aioId = aioId;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return this.archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public int getOaiPmhId() {
		return this.oaiPmhId;
	}

	public void setOaiPmhId(int oaiPmhId) {
		this.oaiPmhId = oaiPmhId;
	}

	public String getOaiPmhUrl() {
		return this.oaiPmhUrl;
	}

	public void setOaiPmhUrl(String oaiPmhUrl) {
		this.oaiPmhUrl = oaiPmhUrl;
	}

	public Date getLastHarvesting() {
		return this.lastHarvesting;
	}

	public void setLastHarvesting(Date lastHarvesting) {
		this.lastHarvesting = lastHarvesting;
	}

}
