package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ArchivalInstitutionOaiPmh generated by hbm2java
 */
public class ArchivalInstitutionOaiPmh implements java.io.Serializable {

	private int aioId;
	private ArchivalInstitution archivalInstitution;
	private int oaiPmhId;
	private String oaiPmhUrl;
	private Date lastHarvesting;

	public ArchivalInstitutionOaiPmh() {
	}

	public ArchivalInstitutionOaiPmh(int aioId,
			ArchivalInstitution archivalInstitution, int oaiPmhId,
			String oaiPmhUrl) {
		this.aioId = aioId;
		this.archivalInstitution = archivalInstitution;
		this.oaiPmhId = oaiPmhId;
		this.oaiPmhUrl = oaiPmhUrl;
	}

	public ArchivalInstitutionOaiPmh(int aioId,
			ArchivalInstitution archivalInstitution, int oaiPmhId,
			String oaiPmhUrl, Date lastHarvesting) {
		this.aioId = aioId;
		this.archivalInstitution = archivalInstitution;
		this.oaiPmhId = oaiPmhId;
		this.oaiPmhUrl = oaiPmhUrl;
		this.lastHarvesting = lastHarvesting;
	}

	public int getAioId() {
		return this.aioId;
	}

	public void setAioId(int aioId) {
		this.aioId = aioId;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return this.archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public int getOaiPmhId() {
		return this.oaiPmhId;
	}

	public void setOaiPmhId(int oaiPmhId) {
		this.oaiPmhId = oaiPmhId;
	}

	public String getOaiPmhUrl() {
		return this.oaiPmhUrl;
	}

	public void setOaiPmhUrl(String oaiPmhUrl) {
		this.oaiPmhUrl = oaiPmhUrl;
	}

	public Date getLastHarvesting() {
		return this.lastHarvesting;
	}

	public void setLastHarvesting(Date lastHarvesting) {
		this.lastHarvesting = lastHarvesting;
	}

}
