package eu.apenet.persistence.vo;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CollectionContent generated by hbm2java
 */
@Entity
@Table(name = "collection_content")
public class CollectionContent implements java.io.Serializable {

	private long id;
	private Collection collection;
	private SavedBookmarks savedBookmarks;
	private EadSavedSearch eadSavedSearch;

	public CollectionContent() {
	}

	public CollectionContent(long id, Collection collection) {
		this.id = id;
		this.collection = collection;
	}

	public CollectionContent(long id, Collection collection,
			SavedBookmarks savedBookmarks, EadSavedSearch eadSavedSearch) {
		this.id = id;
		this.collection = collection;
		this.savedBookmarks = savedBookmarks;
		this.eadSavedSearch = eadSavedSearch;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_collection", nullable = false)
	public Collection getCollection() {
		return this.collection;
	}

	public void setCollection(Collection collection) {
		this.collection = collection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bookmarks")
	public SavedBookmarks getSavedBookmarks() {
		return this.savedBookmarks;
	}

	public void setSavedBookmarks(SavedBookmarks savedBookmarks) {
		this.savedBookmarks = savedBookmarks;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_search")
	public EadSavedSearch getEadSavedSearch() {
		return this.eadSavedSearch;
	}

	public void setEadSavedSearch(EadSavedSearch eadSavedSearch) {
		this.eadSavedSearch = eadSavedSearch;
	}

}
