package eu.apenet.persistence.vo;

// Generated 01-ago-2014 13:50:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Collection generated by hbm2java
 */
@Entity
@Table(name = "collection", schema = "public")
public class Collection implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id")
	private Long id;
	@Column(name = "title", length = 200)
	private String title;
	@Column(name = "description")
	private String description;
	@Column(name = "liferay_user_id", nullable = false)
	private long liferayUserId;
	@Column(name = "public", nullable = false)
	private boolean public_;
	@Column(name = "edit", nullable = false)
	private boolean edit;

	public Collection() {
	}


	public Collection(long id, String title, long liferayUserId, boolean public_,
			boolean edit) {
		this.id = id;
		this.title = title;
		this.liferayUserId = liferayUserId;
		this.public_ = public_;
		this.edit = edit;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getLiferayUserId() {
		return this.liferayUserId;
	}

	public void setLiferayUserId(long liferayUserId) {
		this.liferayUserId = liferayUserId;
	}

	public boolean isPublic_() {
		return this.public_;
	}

	public void setPublic_(boolean public_) {
		this.public_ = public_;
	}

	public boolean isEdit() {
		return this.edit;
	}

	public void setEdit(boolean edit) {
		this.edit = edit;
	}
}
