package eu.apenet.persistence.vo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 25-ene-2011 16:20:03 by Hibernate Tools 3.2.4.GA

/**
 * CouAlternativeName generated by hbm2java
 */
@Entity
@Table(name = "cou_alternative_name")
public class CouAlternativeName implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3066002700057560525L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id")
	private int couAnId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lng_id", foreignKey = @ForeignKey(name="lng_id"))
	private Lang lang;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cou_id", foreignKey = @ForeignKey(name="country_cou_id_fkey"))
	private Country country;
	@Column(name = "cou_an_name")
	private String couAnName;

	public CouAlternativeName() {
	}

	public CouAlternativeName(int couAnId, Lang lang, Country country,
			String couAnName) {
		this.couAnId = couAnId;
		this.lang = lang;
		this.country = country;
		this.couAnName = couAnName;
	}

	public int getCouAnId() {
		return this.couAnId;
	}

	public void setCouAnId(int couAnId) {
		this.couAnId = couAnId;
	}

	public Lang getLang() {
		return this.lang;
	}

	public void setLang(Lang lang) {
		this.lang = lang;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getCouAnName() {
		return this.couAnName;
	}

	public void setCouAnName(String couAnName) {
		this.couAnName = couAnName;
	}

}
