package eu.apenet.persistence.vo;
// Generated 22-oct-2010 12:56:16 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

/**
 * Country generated by hbm2java
 */
@Entity
public class Country implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2051604497193212861L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id")
	private int couId;
	private String cname;
	private String isoname;
	@Column(name = "al_order")
	private int alOrder;
	@OneToMany(mappedBy="country")
	private Set<CouAlternativeName> couAlternativeNames = new HashSet<CouAlternativeName>(0);
	@OneToMany(mappedBy="country")
	private Set<ArchivalInstitution> archivalInstitutions = new HashSet<ArchivalInstitution>(0);
	public Country() {
	}

	public Country(int couId, String cname, String isoname,int alOrder) {
		this.couId = couId;
		this.cname = cname;
		this.isoname = isoname;
		this.alOrder = alOrder;
	}

    public Country(String cname, String isoname, int alOrder) {
		this.cname = cname;
		this.isoname = isoname;
		this.alOrder = alOrder;
	}

	
	public int getAlOrder() {
		return alOrder;
	}

	public void setAlOrder(int alOrder) {
		this.alOrder = alOrder;
	}

	
	public int getCouId() {
		return this.couId;
	}

	public void setCouId(int couId) {
		this.couId = couId;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getIsoname() {
		return this.isoname;
	}

	public void setIsoname(String isoname) {
		this.isoname = isoname;
	}

	public void setCouAlternativeNames(Set<CouAlternativeName> couAlternativeNames) {
		this.couAlternativeNames = couAlternativeNames;
	}

	public Set<CouAlternativeName> getCouAlternativeNames() {
		return couAlternativeNames;
	}

	public Set<ArchivalInstitution> getArchivalInstitutions() {
		return archivalInstitutions;
	}

	public void setArchivalInstitutions(Set<ArchivalInstitution> archivalInstitutions) {
		this.archivalInstitutions = archivalInstitutions;
	}

}
