package eu.apenet.persistence.vo;

// Generated 04-feb-2014 17:50:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CpfContent generated by hbm2java
 */
@Entity
@Table(name = "cpf_content", schema = "public")
public class CpfContent implements java.io.Serializable {

	private long id;
	private EacCpf eacCpf;
	private String cpfId;
	private String xml;
	private Boolean visible;
	private String entityId;
	private boolean displayIntro;

	public CpfContent() {
	}

	public CpfContent(long id, String cpfId, boolean displayIntro) {
		this.id = id;
		this.cpfId = cpfId;
		this.displayIntro = displayIntro;
	}

	public CpfContent(long id, EacCpf eacCpf, String cpfId, String xml,
			Boolean visible, String entityId, boolean displayIntro) {
		this.id = id;
		this.eacCpf = eacCpf;
		this.cpfId = cpfId;
		this.xml = xml;
		this.visible = visible;
		this.entityId = entityId;
		this.displayIntro = displayIntro;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eac_cpf_id")
	public EacCpf getEacCpf() {
		return this.eacCpf;
	}

	public void setEacCpf(EacCpf eacCpf) {
		this.eacCpf = eacCpf;
	}

	@Column(name = "cpf_id", nullable = false)
	public String getCpfId() {
		return this.cpfId;
	}

	public void setCpfId(String cpfId) {
		this.cpfId = cpfId;
	}

	@Column(name = "xml")
	public String getXml() {
		return this.xml;
	}

	public void setXml(String xml) {
		this.xml = xml;
	}

	@Column(name = "visible")
	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	@Column(name = "entity_id")
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@Column(name = "display_intro", nullable = false)
	public boolean isDisplayIntro() {
		return this.displayIntro;
	}

	public void setDisplayIntro(boolean displayIntro) {
		this.displayIntro = displayIntro;
	}

}
