package eu.apenet.persistence.vo;

// Generated 20-abr-2011 12:04:49 by Hibernate Tools 3.2.4.GA
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ese generated by hbm2java
 */
@Entity
@Table(name = "ese")
public class Ese implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -1880474004952476059L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer eseId;

    @Column(name = "creation_date")
    private Date creationDate;

    private String eset;

    @Column(name = "modification_date")
    private Date modificationDate;

    @Column(name = "number_of_records")
    private Integer numberOfRecords;

    @Column(name = "number_of_web_resource")
    private Integer numberOfWebResource;

    @Column(name = "oai_identifier")
    private String oaiIdentifier;

    private String path;

    @Column(name = "path_html")
    private String pathHtml;

    //bi-directional many-to-one association to EseState
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "es_id", foreignKey = @ForeignKey(name = "ese_es_id_fkey"))
    private EseState eseState;

    //bi-directional many-to-one association to FindingAid
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fa_id", foreignKey = @ForeignKey(name = "ese_fa_id_fkey"))
    private FindingAid findingAid;

    @Enumerated(EnumType.STRING)
    private MetadataFormat metadataFormat = MetadataFormat.EDM;

    public Ese() {
    }

    public Ese(int eseId, MetadataFormat metadataFormat, EseState eseState,
            Date creationDate, String eset, String path, String oaiIdentifier) {
        this.eseId = eseId;
        this.metadataFormat = metadataFormat;
        this.eseState = eseState;
        this.creationDate = creationDate;
        this.eset = eset;
        this.path = path;
        this.oaiIdentifier = oaiIdentifier;
    }

    @Deprecated
    public Ese(int eseId, MetadataFormat metadataFormat, EseState eseState,
            FindingAid findingAid, Date creationDate, Date modificationDate,
            String eset, String path, String pathHtml, Integer numberOfRecords,
            String oaiIdentifier) {
        this.eseId = eseId;
        this.metadataFormat = metadataFormat;
        this.eseState = eseState;
        this.findingAid = findingAid;
        this.creationDate = creationDate;
        this.modificationDate = modificationDate;
        this.eset = eset;
        this.path = path;
        this.pathHtml = pathHtml;
        this.numberOfRecords = numberOfRecords;
        this.oaiIdentifier = oaiIdentifier;
    }

    public int getEseId() {
        return this.eseId;
    }

    public void setEseId(int eseId) {
        this.eseId = eseId;
    }

    public MetadataFormat getMetadataFormat() {
        return this.metadataFormat;
    }

    public void setMetadataFormat(MetadataFormat metadataFormat) {
        this.metadataFormat = metadataFormat;
    }

    public EseState getEseState() {
        return this.eseState;
    }

    public void setEseState(EseState eseState) {
        this.eseState = eseState;
    }

    public FindingAid getFindingAid() {
        return this.findingAid;
    }

    public void setFindingAid(FindingAid findingAid) {
        this.findingAid = findingAid;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getModificationDate() {
        return this.modificationDate;
    }

    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    public String getEset() {
        return this.eset;
    }

    public void setEset(String eset) {
        this.eset = eset;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getPathHtml() {
        return this.pathHtml;
    }

    public void setPathHtml(String pathHtml) {
        this.pathHtml = pathHtml;
    }

    public Integer getNumberOfRecords() {
        return this.numberOfRecords;
    }

    public void setNumberOfRecords(Integer numberOfRecords) {
        this.numberOfRecords = numberOfRecords;
    }

    public void setOaiIdentifier(String oaiIdentifier) {
        this.oaiIdentifier = oaiIdentifier;
    }

    public String getOaiIdentifier() {
        return oaiIdentifier;
    }

    public Integer getNumberOfWebResource() {
        return numberOfWebResource;
    }

    public void setNumberOfWebResource(Integer numberOfWebResource) {
        this.numberOfWebResource = numberOfWebResource;
    }
}
