package eu.apenet.persistence.vo;

// Generated 20-abr-2011 12:04:49 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ese generated by hbm2java
 */
public class Ese implements java.io.Serializable {

	private int eseId;
	private MetadataFormat metadataFormat;
	private EseState eseState;
	private FindingAid findingAid;
	private Date creationDate;
	private Date modificationDate;
	private String eset;
	private String path;
	private String pathHtml;
	private Integer numberOfRecords;
	private String oaiIdentifier;
	public Ese() {
	}

	public Ese(int eseId, MetadataFormat metadataFormat, EseState eseState,
			Date creationDate, String eset, String path, String oaiIdentifier) {
		this.eseId = eseId;
		this.metadataFormat = metadataFormat;
		this.eseState = eseState;
		this.creationDate = creationDate;
		this.eset = eset;
		this.path = path;
		this.oaiIdentifier = oaiIdentifier;
	}
	@Deprecated
	public Ese(int eseId, MetadataFormat metadataFormat, EseState eseState,
			FindingAid findingAid, Date creationDate, Date modificationDate,
			String eset, String path, String pathHtml, Integer numberOfRecords,
			String oaiIdentifier) {
		this.eseId = eseId;
		this.metadataFormat = metadataFormat;
		this.eseState = eseState;
		this.findingAid = findingAid;
		this.creationDate = creationDate;
		this.modificationDate = modificationDate;
		this.eset = eset;
		this.path = path;
		this.pathHtml = pathHtml;
		this.numberOfRecords = numberOfRecords;
		this.oaiIdentifier = oaiIdentifier;
	}

	public int getEseId() {
		return this.eseId;
	}

	public void setEseId(int eseId) {
		this.eseId = eseId;
	}

	public MetadataFormat getMetadataFormat() {
		return this.metadataFormat;
	}

	public void setMetadataFormat(MetadataFormat metadataFormat) {
		this.metadataFormat = metadataFormat;
	}

	public EseState getEseState() {
		return this.eseState;
	}

	public void setEseState(EseState eseState) {
		this.eseState = eseState;
	}

	public FindingAid getFindingAid() {
		return this.findingAid;
	}

	public void setFindingAid(FindingAid findingAid) {
		this.findingAid = findingAid;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public String getEset() {
		return this.eset;
	}

	public void setEset(String eset) {
		this.eset = eset;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getPathHtml() {
		return this.pathHtml;
	}

	public void setPathHtml(String pathHtml) {
		this.pathHtml = pathHtml;
	}

	public Integer getNumberOfRecords() {
		return this.numberOfRecords;
	}

	public void setNumberOfRecords(Integer numberOfRecords) {
		this.numberOfRecords = numberOfRecords;
	}

	public void setOaiIdentifier(String oaiIdentifier) {
		this.oaiIdentifier = oaiIdentifier;
	}

	public String getOaiIdentifier() {
		return oaiIdentifier;
	}

}