package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EseState generated by hbm2java
 */
public class EseState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4300947370980070120L;
	public static final String NOT_PUBLISHED = "Not published";
	public static final String PUBLISHED = "Published";
	public static final String REMOVED = "Removed";

	private int esId;
	private String state;

	public EseState() {
	}

	public EseState(int esId, String state) {
		this.esId = esId;
		this.state = state;
	}


	public int getEsId() {
		return this.esId;
	}

	public void setEsId(int esId) {
		this.esId = esId;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
