package eu.apenet.persistence.vo;
// Generated 04-oct-2010 12:57:39 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * FileType generated by hbm2java
 */
public class FileType implements java.io.Serializable {
    public static final String ZIP = "zip";
    public static final String XML = "xml";
    public static final String XSL = "xsl";

	private int ftId;
	private String ftype;
	private Set<UpFile> upFiles = new HashSet<UpFile>(0);

	public FileType() {
	}

	public FileType(int ftId, String ftype) {
		this.ftId = ftId;
		this.ftype = ftype;
	}

	public FileType(int ftId, String ftype, Set<UpFile> upFiles) {
		this.ftId = ftId;
		this.ftype = ftype;
		this.upFiles = upFiles;
	}

	public int getFtId() {
		return this.ftId;
	}

	public void setFtId(int ftId) {
		this.ftId = ftId;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public Set<UpFile> getUpFiles() {
		return this.upFiles;
	}

	public void setUpFiles(Set<UpFile> upFiles) {
		this.upFiles = upFiles;
	}

}
