package eu.apenet.persistence.vo;
// Generated 04-oct-2010 12:57:39 by Hibernate Tools 3.2.4.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FileType generated by hbm2java
 */
@Entity
@Table(name = "file_type")
public class FileType implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7851583957077039819L;
	public static final String ZIP = "zip";
    public static final String XML = "xml";
    public static final String XSL = "xsl";
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	private String ftype;

	public FileType() {
	}



	public int getId() {
		return id;
	}



	public void setId(int id) {
		this.id = id;
	}



	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}



}
