package eu.apenet.persistence.vo;

import java.util.Date;
// Generated 10-may-2011 9:45:34 by Hibernate Tools 3.2.4.GA

/**
 * IndexQueue generated by hbm2java
 */
public class IndexQueue implements java.io.Serializable {

	private int iqId;
	private HoldingsGuide holdingsGuide;
	private FindingAid findingAid;
	private SourceGuide sourceGuide;
	private int position;
	private Date queueDate;
	private FileState fileState;
	private String errors;

	public IndexQueue() {
	}

	public IndexQueue(int iqId) {
		this.iqId = iqId;
	}

	public IndexQueue(int iqId, HoldingsGuide holdingsGuide,
			FindingAid findingAid, int position, Date queueDate, FileState fileState, String errors) {
		this.iqId = iqId;
		this.holdingsGuide = holdingsGuide;
		this.findingAid = findingAid;
		this.position = position;
		this.queueDate = queueDate;
		this.setFileState(fileState);
		this.setErrors(errors);
	}

	public int getIqId() {
		return this.iqId;
	}

	public void setIqId(int iqId) {
		this.iqId = iqId;
	}

	public HoldingsGuide getHoldingsGuide() {
		return this.holdingsGuide;
	}

	public void setHoldingsGuide(HoldingsGuide holdingsGuide) {
		this.holdingsGuide = holdingsGuide;
	}

	public FindingAid getFindingAid() {
		return this.findingAid;
	}

	public void setFindingAid(FindingAid findingAid) {
		this.findingAid = findingAid;
	}

    public SourceGuide getSourceGuide() {
        return sourceGuide;
    }

    public void setSourceGuide(SourceGuide sourceGuide) {
        this.sourceGuide = sourceGuide;
    }

    public void setPosition(int position) {
		this.position = position;
	}

	public int getPosition() {
		return position;
	}

	public Date getQueueDate() {
		return queueDate;
	}

	public void setQueueDate(Date queueDate) {
		this.queueDate = queueDate;
	}

	public void setFileState(FileState fileState) {
		this.fileState = fileState;
	}

	public FileState getFileState() {
		return fileState;
	}

	public String getErrors() {
		return errors;
	}

	public void setErrors(String errors) {
		this.errors = errors;
	}





}
