package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private ItemId id;
	private LevelType levelType;
	private NormalUser normalUser;
	private String label;

	public Item() {
	}

	public Item(ItemId id, LevelType levelType, NormalUser normalUser,
			String label) {
		this.id = id;
		this.levelType = levelType;
		this.normalUser = normalUser;
		this.label = label;
	}

	public ItemId getId() {
		return this.id;
	}

	public void setId(ItemId id) {
		this.id = id;
	}

	public LevelType getLevelType() {
		return this.levelType;
	}

	public void setLevelType(LevelType levelType) {
		this.levelType = levelType;
	}

	public NormalUser getNormalUser() {
		return this.normalUser;
	}

	public void setNormalUser(NormalUser normalUser) {
		this.normalUser = normalUser;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
