package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

/**
 * ItemId generated by hbm2java
 */
public class ItemId implements java.io.Serializable {

	private int itId;
	private int UId;

	public ItemId() {
	}

	public ItemId(int itId, int UId) {
		this.itId = itId;
		this.UId = UId;
	}

	public int getItId() {
		return this.itId;
	}

	public void setItId(int itId) {
		this.itId = itId;
	}

	public int getUId() {
		return this.UId;
	}

	public void setUId(int UId) {
		this.UId = UId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemId))
			return false;
		ItemId castOther = (ItemId) other;

		return (this.getItId() == castOther.getItId())
				&& (this.getUId() == castOther.getUId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItId();
		result = 37 * result + this.getUId();
		return result;
	}

}
