package eu.apenet.persistence.vo;
// Generated 19-ene-2011 16:06:41 by Hibernate Tools 3.2.4.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * Lang generated by hbm2java
 */
@Entity
public class Lang implements Comparable<Lang>, java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7009188844233308348L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	private String lname;
	private String isoname;
	private String iso2name;
	private String lnativename;

	public Lang() {
	}

	public Lang(int lngId, String lname, String isoname, String iso2name,
			String lnativename) {
		this.id = lngId;
		this.lname = lname;
		this.isoname = isoname;
		this.iso2name = iso2name;
		this.lnativename = lnativename;
	}


    public Lang(String lname, String isoname, String iso2name, String lnativename) {
		this.lname = lname;
		this.isoname = isoname;
		this.iso2name = iso2name;
		this.lnativename = lnativename;
	}



	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getIsoname() {
		return this.isoname;
	}

	public void setIsoname(String isoname) {
		this.isoname = isoname;
	}

	public String getIso2name() {
		return this.iso2name;
	}

	public void setIso2name(String iso2name) {
		this.iso2name = iso2name;
	}

	public String getLnativename() {
		return this.lnativename;
	}

	public void setLnativename(String lnativename) {
		this.lnativename = lnativename;
	}


	@Override
	public int compareTo(Lang o) {
		return this.getLname().toString().compareTo((o).getLname().toString());
	}
}
