package eu.apenet.persistence.vo;
// Generated 19-ene-2011 16:06:41 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Lang generated by hbm2java
 */
public class Lang implements Comparable, java.io.Serializable{

	private int lngId;
	private String lname;
	private String isoname;
	private String iso2name;
	private String lnativename;
	private Set<CouAlternativeName> couAlternativeNames = new HashSet<CouAlternativeName>(0);
	private Set<AiAlternativeName> aiAlternativeNames = new HashSet<AiAlternativeName>(0);

	public Lang() {
	}

	public Lang(int lngId, String lname, String isoname, String iso2name,
			String lnativename) {
		this.lngId = lngId;
		this.lname = lname;
		this.isoname = isoname;
		this.iso2name = iso2name;
		this.lnativename = lnativename;
	}

	public Lang(int lngId, String lname, String isoname, String iso2name,
			String lnativename, 
			Set<AiAlternativeName> aiAlternativeNames) {
		this.lngId = lngId;
		this.lname = lname;
		this.isoname = isoname;
		this.iso2name = iso2name;
		this.lnativename = lnativename;
		this.aiAlternativeNames = aiAlternativeNames;
	}

    public Lang(String lname, String isoname, String iso2name, String lnativename) {
		this.lname = lname;
		this.isoname = isoname;
		this.iso2name = iso2name;
		this.lnativename = lnativename;
	}

	public int getLngId() {
		return this.lngId;
	}

	public void setLngId(int lngId) {
		this.lngId = lngId;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getIsoname() {
		return this.isoname;
	}

	public void setIsoname(String isoname) {
		this.isoname = isoname;
	}

	public String getIso2name() {
		return this.iso2name;
	}

	public void setIso2name(String iso2name) {
		this.iso2name = iso2name;
	}

	public String getLnativename() {
		return this.lnativename;
	}

	public void setLnativename(String lnativename) {
		this.lnativename = lnativename;
	}

	public Set<AiAlternativeName> getAiAlternativeNames() {
		return this.aiAlternativeNames;
	}

	public void setAiAlternativeNames(Set<AiAlternativeName> aiAlternativeNames) {
		this.aiAlternativeNames = aiAlternativeNames;
	}

	public Set<CouAlternativeName> getCouAlternativeNames() {
		return this.couAlternativeNames;
	}

	public void setCouAlternativeNames(Set<CouAlternativeName> couAlternativeNames) {
		this.couAlternativeNames = couAlternativeNames;
	}

	@Override
	public int compareTo(Object o) {
		if(o instanceof Lang){
			return this.getLname().toString().compareTo(((Lang)o).getLname().toString());
		}
		return 0;
	}
}
