package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * LevelType generated by hbm2java
 */
public class LevelType implements java.io.Serializable {

	private int ltId;
	private String ltype;
	private Set<Item> items = new HashSet<Item>(0);

	private LevelType() {
	}

	private LevelType(int ltId, String ltype) {
		this.ltId = ltId;
		this.ltype = ltype;
	}

	private LevelType(int ltId, String ltype, Set<Item> items) {
		this.ltId = ltId;
		this.ltype = ltype;
		this.items = items;
	}

	public int getLtId() {
		return this.ltId;
	}

	public void setLtId(int ltId) {
		this.ltId = ltId;
	}

	public String getLtype() {
		return this.ltype;
	}

	public void setLtype(String ltype) {
		this.ltype = ltype;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
