package eu.apenet.persistence.vo;

// Generated 04-abr-2011 10:01:29 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetadataFormat generated by hbm2java
 */
@Entity
@Table(name = "metadata_format")
public class MetadataFormat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 843102288806021816L;
	public static final String ESE = "ese";
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id")	
	private int mfId;
	private String format;

	public MetadataFormat() {
	}

	public MetadataFormat(int mfId, String format) {
		this.mfId = mfId;
		this.format = format;
	}


	public int getMfId() {
		return this.mfId;
	}

	public void setMfId(int mfId) {
		this.mfId = mfId;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}


}
