package eu.apenet.persistence.vo;

// Generated 04-abr-2011 10:01:29 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MetadataFormat generated by hbm2java
 */
public class MetadataFormat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 843102288806021816L;
	public static final String ESE = "ese";
	private int mfId;
	private String format;
	private Set<ResumptionToken> resumptionTokens = new HashSet<ResumptionToken>(
			0);

	public MetadataFormat() {
	}

	public MetadataFormat(int mfId, String format) {
		this.mfId = mfId;
		this.format = format;
	}

	public MetadataFormat(int mfId, String format, 
			Set<ResumptionToken> resumptionTokens) {
		this.mfId = mfId;
		this.format = format;
		this.resumptionTokens = resumptionTokens;
	}

	public int getMfId() {
		return this.mfId;
	}

	public void setMfId(int mfId) {
		this.mfId = mfId;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}


	public Set<ResumptionToken> getResumptionTokens() {
		return this.resumptionTokens;
	}

	public void setResumptionTokens(Set<ResumptionToken> resumptionTokens) {
		this.resumptionTokens = resumptionTokens;
	}

}
