package eu.apenet.persistence.vo;
// Generated 22-oct-2010 13:45:44 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * NormalUser generated by hbm2java
 */
public class NormalUser implements java.io.Serializable {

	private Long UId;
	private UserState userState;
	private String nick;
	private String emailAddress;
	private String pwd;
	private String secretQuestion;
	private String secretAnswer;
	private Set<SentMailRegister> sentMailRegisters = new HashSet<SentMailRegister>(
			0);
	private Set<Searches> searcheses = new HashSet<Searches>(0);
	private Set<Item> items = new HashSet<Item>(0);

	private NormalUser() {
	}

	private NormalUser(Long UId, UserState userState, String nick,
			String emailAddress, String pwd) {
		this.UId = UId;
		this.userState = userState;
		this.nick = nick;
		this.emailAddress = emailAddress;
		this.pwd = pwd;
	}
	
	
	private NormalUser(UserState userState, String nick,
			String emailAddress, String pwd) {
		this.userState = userState;
		this.nick = nick;
		this.emailAddress = emailAddress;
		this.pwd = pwd;
	}

	private NormalUser(Long UId, UserState userState, String nick,
			String emailAddress, String pwd, String secretQuestion,
			String secretAnswer, Set<SentMailRegister> sentMailRegisters,
			Set<Searches> searcheses,
			Set<Item> items) {
		this.UId = UId;
		this.userState = userState;
		this.nick = nick;
		this.emailAddress = emailAddress;
		this.pwd = pwd;
		this.secretQuestion = secretQuestion;
		this.secretAnswer = secretAnswer;
		this.sentMailRegisters = sentMailRegisters;
		this.searcheses = searcheses;
		this.items = items;
	}

	public Long getUId() {
		return this.UId;
	}

	public void setUId(Long UId) {
		this.UId = UId;
	}

	public UserState getUserState() {
		return this.userState;
	}

	public void setUserState(UserState userState) {
		this.userState = userState;
	}

	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getSecretQuestion() {
		return this.secretQuestion;
	}

	public void setSecretQuestion(String secretQuestion) {
		this.secretQuestion = secretQuestion;
	}

	public String getSecretAnswer() {
		return this.secretAnswer;
	}

	public void setSecretAnswer(String secretAnswer) {
		this.secretAnswer = secretAnswer;
	}

	public Set<SentMailRegister> getSentMailRegisters() {
		return this.sentMailRegisters;
	}

	public void setSentMailRegisters(Set<SentMailRegister> sentMailRegisters) {
		this.sentMailRegisters = sentMailRegisters;
	}


	public Set<Searches> getSearcheses() {
		return this.searcheses;
	}

	public void setSearcheses(Set<Searches> searcheses) {
		this.searcheses = searcheses;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("persistencia.vo.NormalUser:");
		ret.append("u_id='"+UId+"'");
		//ret.append("us_id='"+userState.getUsId()+"'");
		ret.append(", nick='"+nick+"'");
		ret.append(", password='"+pwd+"'");
		ret.append(", email_address='"+emailAddress+"'");
		return ret.toString();
	}

	
}