package eu.apenet.persistence.vo;

// Generated 04-abr-2011 10:01:29 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ResumptionToken generated by hbm2java
 */
public class ResumptionToken implements java.io.Serializable {

	private int rtId;
	private MetadataFormat metadataFormat;
	private Date expirationDate;
	private Date fromDate;
	private Date untilDate;
	private String set;
	private String lastRecordHarvested;

	public ResumptionToken() {
	}

	public ResumptionToken(int rtId, Date expirationDate, Date fromDate,
			Date untilDate, String lastRecordHarvested) {
		this.rtId = rtId;
		this.expirationDate = expirationDate;
		this.fromDate = fromDate;
		this.untilDate = untilDate;
		this.lastRecordHarvested = lastRecordHarvested;
	}

	public ResumptionToken(int rtId, MetadataFormat metadataFormat,
			Date expirationDate, Date fromDate, Date untilDate, String set,
			String lastRecordHarvested) {
		this.rtId = rtId;
		this.metadataFormat = metadataFormat;
		this.expirationDate = expirationDate;
		this.fromDate = fromDate;
		this.untilDate = untilDate;
		this.set = set;
		this.lastRecordHarvested = lastRecordHarvested;
	}

	public int getRtId() {
		return this.rtId;
	}

	public void setRtId(int rtId) {
		this.rtId = rtId;
	}

	public MetadataFormat getMetadataFormat() {
		return this.metadataFormat;
	}

	public void setMetadataFormat(MetadataFormat metadataFormat) {
		this.metadataFormat = metadataFormat;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getUntilDate() {
		return this.untilDate;
	}

	public void setUntilDate(Date untilDate) {
		this.untilDate = untilDate;
	}

	public String getSet() {
		return this.set;
	}

	public void setSet(String set) {
		this.set = set;
	}

	public String getLastRecordHarvested() {
		return this.lastRecordHarvested;
	}

	public void setLastRecordHarvested(String lastRecordHarvested) {
		this.lastRecordHarvested = lastRecordHarvested;
	}

}
