package eu.apenet.persistence.vo;

//Generated 28-oct-2011 13:12:16 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
* Searches generated by hbm2java
*/
public class Searches implements java.io.Serializable {

	private Long seaId;
	private NormalUser normalUser;
	private String searchString;
	private String label;
	private Date date;
	private String view;
	private String navTreeLang;
	private Integer resultsperpage;
	private String searchButton;
	private String element;
	private String fromDate;
	private String toDate;
	private String typedocument;
	private String dao;
	private String method;
	private String navigationTreeNodesSelected;
	private String expandedNodes;
	private String order;
	private String startdate;
	private String enddate;
	private String ai;
	private String type;
	private String datetype;
	private String country;
	private String pagenumber;

	public Searches() {
	}

	public Searches(Long seaId, NormalUser normalUser, String searchString,
			Date date, String view) {
		this.seaId = seaId;
		this.normalUser = normalUser;
		this.searchString = searchString;
		this.date = date;
		this.view = view;
	}

	
	/*
	public Searches(Long seaId, NormalUser normalUser, String searchString,
			String label, Date date, String view, String navTreeLang,
			Integer resultsperpage, String searchButton, String element,
			String fromDate, String toDate, String typedocument, String dao,
			String method, String navigationTreeNodesSelected,
			String expandedNodes) {
		this.seaId = seaId;
		this.normalUser = normalUser;
		this.searchString = searchString;
		this.label = label;
		this.date = date;
		this.view = view;
		this.navTreeLang = navTreeLang;
		this.resultsperpage = resultsperpage;
		this.searchButton = searchButton;
		this.element = element;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.typedocument = typedocument;
		this.dao = dao;
		this.method = method;
		this.navigationTreeNodesSelected = navigationTreeNodesSelected;
		this.expandedNodes = expandedNodes;
	}
	
	public Searches(long seaId, NormalUser normalUser, String searchString,
			String label, Date date, String view, String navtreelang,
			Integer resultsperpage, String searchbutton, String element,
			String fromdate, String todate, String typedocument, String dao,
			String method, String navigationtreenodesselected,
			String expandednodes, String order, String startdate,
			String enddate, String ai, String type, String datetype,
			String country, String pagenumber) {
		this.seaId = seaId;
		this.normalUser = normalUser;
		this.searchString = searchString;
		this.label = label;
		this.date = date;
		this.view = view;
		this.navtreelang = navtreelang;
		this.resultsperpage = resultsperpage;
		this.searchbutton = searchbutton;
		this.element = element;
		this.fromdate = fromdate;
		this.todate = todate;
		this.typedocument = typedocument;
		this.dao = dao;
		this.method = method;
		this.navigationtreenodesselected = navigationtreenodesselected;
		this.expandednodes = expandednodes;
		this.order = order;
		this.startdate = startdate;
		this.enddate = enddate;
		this.ai = ai;
		this.type = type;
		this.datetype = datetype;
		this.country = country;
		this.pagenumber = pagenumber;
	}
	*/
	
	


	public Searches(Long seaId, NormalUser normalUser, String searchString,
			String label, Date date, String view, String navTreeLang,
			Integer resultsperpage, String searchButton, String element,
			String fromDate, String toDate, String typedocument, String dao,
			String method, String navigationTreeNodesSelected,
			String expandedNodes, String order, String startdate,
			String enddate, String ai, String type, String datetype,
			String country, String pagenumber) {
		super();
		this.seaId = seaId;
		this.normalUser = normalUser;
		this.searchString = searchString;
		this.label = label;
		this.date = date;
		this.view = view;
		this.navTreeLang = navTreeLang;
		this.resultsperpage = resultsperpage;
		this.searchButton = searchButton;
		this.element = element;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.typedocument = typedocument;
		this.dao = dao;
		this.method = method;
		this.navigationTreeNodesSelected = navigationTreeNodesSelected;
		this.expandedNodes = expandedNodes;
		this.order = order;
		this.startdate = startdate;
		this.enddate = enddate;
		this.ai = ai;
		this.type = type;
		this.datetype = datetype;
		this.country = country;
		this.pagenumber = pagenumber;
	}

	
	
	public String getOrder() {
		return order;
	}
	
	public void setOrder(String order) {
		this.order = order;
	}

	public String getStartdate() {
		return startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	public String getEnddate() {
		return enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public String getAi() {
		return ai;
	}

	public void setAi(String ai) {
		this.ai = ai;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDatetype() {
		return datetype;
	}

	public void setDatetype(String datetype) {
		this.datetype = datetype;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPagenumber() {
		return pagenumber;
	}

	public void setPagenumber(String pagenumber) {
		this.pagenumber = pagenumber;
	}
	
	public Long getSeaId() {
		return this.seaId;
	}

	public void setSeaId(Long seaId) {
		this.seaId = seaId;
	}

	public NormalUser getNormalUser() {
		return this.normalUser;
	}

	public void setNormalUser(NormalUser normalUser) {
		this.normalUser = normalUser;
	}

	public String getSearchString() {
		return this.searchString;
	}

	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getView() {
		return this.view;
	}

	public void setView(String view) {
		this.view = view;
	}

	public String getNavTreeLang() {
		return this.navTreeLang;
	}

	public void setNavTreeLang(String navTreeLang) {
		this.navTreeLang = navTreeLang;
	}

	public Integer getResultsperpage() {
		return this.resultsperpage;
	}

	public void setResultsperpage(Integer resultsperpage) {
		this.resultsperpage = resultsperpage;
	}

	public String getSearchButton() {
		return this.searchButton;
	}

	public void setSearchButton(String searchButton) {
		this.searchButton = searchButton;
	}

	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	public String getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return this.toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getTypedocument() {
		return this.typedocument;
	}

	public void setTypedocument(String typedocument) {
		this.typedocument = typedocument;
	}

	public String getDao() {
		return this.dao;
	}

	public void setDao(String dao) {
		this.dao = dao;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getNavigationTreeNodesSelected() {
		return this.navigationTreeNodesSelected;
	}

	public void setNavigationTreeNodesSelected(
			String navigationTreeNodesSelected) {
		this.navigationTreeNodesSelected = navigationTreeNodesSelected;
	}

	public String getExpandedNodes() {
		return this.expandedNodes;
	}

	public void setExpandedNodes(String expandedNodes) {
		this.expandedNodes = expandedNodes;
	}

}


