package eu.apenet.persistence.vo;

// Generated 25-may-2011 10:17:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SentMailRegister generated by hbm2java
 */
public class SentMailRegister implements java.io.Serializable {

	private int smrId;
	private User user;
	private ArchivalInstitution archivalInstitution;
	private String validationLink;
	private Date date;
	private String emailAddress;

	public SentMailRegister() {
	}

	public SentMailRegister(int smrId, String validationLink, Date date,
			String emailAddress) {
		this.smrId = smrId;
		this.validationLink = validationLink;
		this.date = date;
		this.emailAddress = emailAddress;
	}

	
	public SentMailRegister(String validationLink, Date date,
			String emailAddress) {
		this.validationLink = validationLink;
		this.date = date;
		this.emailAddress = emailAddress;
	}



	public int getSmrId() {
		return this.smrId;
	}

	public void setSmrId(int smrId) {
		this.smrId = smrId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User partner) {
		this.user = partner;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return this.archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public String getValidationLink() {
		return this.validationLink;
	}

	public void setValidationLink(String validationLink) {
		this.validationLink = validationLink;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}