package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UpFileState generated by hbm2java
 */
public class UpFileState implements java.io.Serializable {
    public static final String NEW = "New";

	private int ufsId;
	private String state;
	private Set<UpFile> upFiles = new HashSet<UpFile>(0);

	public UpFileState() {
	}

	public UpFileState(int ufsId, String state) {
		this.ufsId = ufsId;
		this.state = state;
	}

	public UpFileState(int ufsId, String state, Set<UpFile> upFiles) {
		this.ufsId = ufsId;
		this.state = state;
		this.upFiles = upFiles;
	}

	public int getUfsId() {
		return this.ufsId;
	}

	public void setUfsId(int ufsId) {
		this.ufsId = ufsId;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set<UpFile> getUpFiles() {
		return this.upFiles;
	}

	public void setUpFiles(Set<UpFile> upFiles) {
		this.upFiles = upFiles;
	}

}
