package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UpFileState generated by hbm2java
 */
@Entity
@Table(name = "up_file_state")
public class UpFileState implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 3167548317958902432L;

	public static final String NEW = "New";
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	private String state;




	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}


}
