package eu.apenet.persistence.vo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

//default package
//Generated 24-sep-2010 15:19:04 by Hibernate Tools 3.2.4.GA

/**
* UpFile generated by hbm2java
*/
@Entity
@Table(name = "up_file")
public class UpFile implements java.io.Serializable {
    public static final String XML_TYPE = "ape.xmltype";
    public static final String NO_EADID_ACTION = "ape.noeadidaction";
    public static final String EXIST_ACTION = "ape.existaction";
    public static final String DAO_TYPE = "ape.daotype";
    public static final String DAO_TYPE_CHECK = "ape.daotypecheck";
    public static final String UPLOAD_ACTION = "ape.uploadaction";
    public static final String CONVERSION_TYPE = "europeana.conversiontype";
    public static final String DATA_PROVIDER = "europeana.dataprovider";
    public static final String DATA_PROVIDER_CHECK = "europeana.dataprovidercheck";
    public static final String EUROPEANA_DAO_TYPE = "europeana.daotype";
    public static final String EUROPEANA_DAO_TYPE_CHECK = "europeana.daotypecheck";
    public static final String LANGUAGES = "europeana.languages";
    public static final String LANGUAGE_CHECK = "europeana.languagecheck";
    public static final String LICENSE = "europeana.license";
    public static final String LICENSE_DETAILS = "europeana.licensedetails";
    public static final String LICENSE_ADD_INFO = "europeana.licenseaddinfo";
    public static final String INHERIT_FILE_CHECK = "europeana.inheritfilecheck";
    public static final String INHERIT_FILE = "europeana.inheritfile";
    public static final String INHERIT_ORIGINATION_CHECK = "europeana.inheritoriginationcheck";
    public static final String INHERIT_ORIGINATION = "europeana.inheritorigination";

	/**
	 * 
	 */
	private static final long serialVersionUID = 1645612482442032830L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id")	
	private int id;
	@Enumerated(EnumType.STRING)
	@Column(name="file_type")
	private FileType fileType;
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="um_id")
	private UploadMethod uploadMethod;
	@Column(name="ai_id")
	private Integer aiId;
	private String path;
	private String filename;
	@ManyToOne(fetch = FetchType.LAZY )
	@JoinColumn(name = "ai_id" , updatable = false, insertable = false)
	private ArchivalInstitution archivalInstitution;
	private String preferences;

	public int getId() {
		return this.id;
	}

	public void setId(int ufId) {
		this.id = ufId;
	}

	public FileType getFileType() {
		return this.fileType;
	}

	public void setFileType(FileType fileType) {
		this.fileType = fileType;
	}

	public UploadMethod getUploadMethod() {
		return this.uploadMethod;
	}

	public void setUploadMethod(UploadMethod uploadMethod) {
		this.uploadMethod = uploadMethod;
	}

	public Integer getAiId() {
		return aiId;
	}

	public void setAiId(Integer aiId) {
		this.aiId = aiId;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public void setFilename(String fname) {
		this.filename = fname;
	}

	public String getFilename() {
		return filename;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public String getPreferences() {
		return preferences;
	}

	public void setPreferences(String preferences) {
		this.preferences = preferences;
	}

}