package eu.apenet.persistence.vo;

import eu.apenet.persistence.vo.ArchivalInstitution;
import eu.apenet.persistence.vo.FileType;
import eu.apenet.persistence.vo.UpFileState;
import eu.apenet.persistence.vo.UploadMethod;

//default package
//Generated 24-sep-2010 15:19:04 by Hibernate Tools 3.2.4.GA

/**
* UpFile generated by hbm2java
*/
public class UpFile implements java.io.Serializable {

	private int ufId;
	private FileType fileType;
	private UpFileState upFileState;
	private UploadMethod uploadMethod;
	private ArchivalInstitution archivalInstitution;
	private String path;
	private String fname;

	public UpFile() {
	}

	public UpFile(int ufId, FileType fileType, UpFileState upFileState,
			UploadMethod uploadMethod, ArchivalInstitution archivalInstitution,
			String path) {
		this.ufId = ufId;
		this.fileType = fileType;
		this.upFileState = upFileState;
		this.uploadMethod = uploadMethod;
		this.archivalInstitution = archivalInstitution;
		this.path = path;
	}

	public int getUfId() {
		return this.ufId;
	}

	public void setUfId(int ufId) {
		this.ufId = ufId;
	}

	public FileType getFileType() {
		return this.fileType;
	}

	public void setFileType(FileType fileType) {
		this.fileType = fileType;
	}

	public UpFileState getUpFileState() {
		return this.upFileState;
	}

	public void setUpFileState(UpFileState upFileState) {
		this.upFileState = upFileState;
	}

	public UploadMethod getUploadMethod() {
		return this.uploadMethod;
	}

	public void setUploadMethod(UploadMethod uploadMethod) {
		this.uploadMethod = uploadMethod;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return this.archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFname() {
		return fname;
	}

}