package eu.apenet.persistence.vo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

//default package
//Generated 24-sep-2010 15:19:04 by Hibernate Tools 3.2.4.GA

/**
* UpFile generated by hbm2java
*/
@Entity
@Table(name = "up_file")
public class UpFile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1645612482442032830L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id")	
	private int ufId;
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ft_id")
	private FileType fileType;
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="um_id")
	private UploadMethod uploadMethod;
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ai_id")
	private ArchivalInstitution archivalInstitution;
	private String path;
	private String fname;

	public UpFile() {
	}

	public UpFile(int ufId, FileType fileType, UploadMethod uploadMethod, ArchivalInstitution archivalInstitution,
			String path) {
		this.ufId = ufId;
		this.fileType = fileType;
		this.uploadMethod = uploadMethod;
		this.archivalInstitution = archivalInstitution;
		this.path = path;
	}

	public int getUfId() {
		return this.ufId;
	}

	public void setUfId(int ufId) {
		this.ufId = ufId;
	}

	public FileType getFileType() {
		return this.fileType;
	}

	public void setFileType(FileType fileType) {
		this.fileType = fileType;
	}

	public UploadMethod getUploadMethod() {
		return this.uploadMethod;
	}

	public void setUploadMethod(UploadMethod uploadMethod) {
		this.uploadMethod = uploadMethod;
	}

	public ArchivalInstitution getArchivalInstitution() {
		return this.archivalInstitution;
	}

	public void setArchivalInstitution(ArchivalInstitution archivalInstitution) {
		this.archivalInstitution = archivalInstitution;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFname() {
		return fname;
	}

}