package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UploadMethod generated by hbm2java
 */
public class UploadMethod implements java.io.Serializable {
    public static final String OAI_PMH = "OAI-PMH";
    public static final String FTP = "FTP";
    public static final String HTTP = "HTTP";

	private int umId;
	private String method;
	private Set<HoldingsGuide> holdingsGuides = new HashSet<HoldingsGuide>(0);
	private Set<UpFile> upFiles = new HashSet<UpFile>(0);
	private Set<FindingAid> findingAids = new HashSet<FindingAid>(0);

	public UploadMethod() {
	}

	public UploadMethod(int umId, String method) {
		this.umId = umId;
		this.method = method;
	}

	public UploadMethod(int umId, String method,
			Set<HoldingsGuide> holdingsGuides, Set<UpFile> upFiles,
			Set<FindingAid> findingAids) {
		this.umId = umId;
		this.method = method;
		this.holdingsGuides = holdingsGuides;
		this.upFiles = upFiles;
		this.findingAids = findingAids;
	}

	public int getUmId() {
		return this.umId;
	}

	public void setUmId(int umId) {
		this.umId = umId;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Set<HoldingsGuide> getHoldingsGuides() {
		return this.holdingsGuides;
	}

	public void setHoldingsGuides(Set<HoldingsGuide> holdingsGuides) {
		this.holdingsGuides = holdingsGuides;
	}

	public Set<UpFile> getUpFiles() {
		return this.upFiles;
	}

	public void setUpFiles(Set<UpFile> upFiles) {
		this.upFiles = upFiles;
	}

	public Set<FindingAid> getFindingAids() {
		return this.findingAids;
	}

	public void setFindingAids(Set<FindingAid> findingAids) {
		this.findingAids = findingAids;
	}

}
