package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UploadMethod generated by hbm2java
 */
@Entity
@Table(name = "upload_method")
public class UploadMethod implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -2467537366763493138L;
	public static final String OAI_PMH = "OAI-PMH";
    public static final String FTP = "FTP";
    public static final String HTTP = "HTTP";
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	private String method;






	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}



}
