package eu.apenet.persistence.vo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA


/**
 * UserState generated by hbm2java
 */
@Entity
@Table(name = "user_state")
public class UserState implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -943247101832707184L;
	public static final String BLOCKED = "Blocked";
    public static final String ACTIVATED = "Actived"; //todo: Change this name to an english name... (also in DB)
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)	
	private Long id;
	private String state;

	public UserState() {
	}



	public UserState(String state) {
		super();
		this.state = state;
	}



	public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}



	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}


}
