package eu.apenet.persistence.vo;

// Generated 09-sep-2010 13:50:04 by Hibernate Tools 3.2.4.GA


/**
 * UserState generated by hbm2java
 */
public class UserState implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -943247101832707184L;
	public static final String BLOCKED = "Blocked";
    public static final String ACTIVATED = "Actived"; //todo: Change this name to an english name... (also in DB)

	private Long usId;
	private String state;

	public UserState() {
	}

	public UserState(Long usId) {
		this.usId = usId;
	}


	public UserState(String state) {
		super();
		this.state = state;
	}

	public Long getUsId() {
		return this.usId;
	}

	public void setUsId(Long usId) {
		this.usId = usId;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}


}
