package eu.apenet.persistence.vo;
// Generated 15-oct-2010 13:00:40 by Hibernate Tools 3.2.4.GA

/**
 * Warnings generated by hbm2java
 */
public class Warnings implements java.io.Serializable {

	private int warId;
	private HoldingsGuide holdingsGuide;
	private FindingAid findingAid;
	private SourceGuide sourceGuide;
	private String abstract_;
	private Boolean iswarning;

	public Warnings() {
	}

	public Warnings(int warId, String abstract_) {
		this.warId = warId;
		this.abstract_ = abstract_;
	}

	public Warnings(int warId, HoldingsGuide holdingsGuide,
			FindingAid findingAid, String abstract_, Boolean iswarning) {
		this.warId = warId;
		this.holdingsGuide = holdingsGuide;
		this.findingAid = findingAid;
		this.abstract_ = abstract_;
		this.iswarning = iswarning;
	}

    public Warnings(String abstract_, boolean iswarning, FindingAid findingAid){
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
        this.findingAid = findingAid;
    }

    public Warnings(String abstract_, boolean iswarning, HoldingsGuide holdingsGuide){
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
        this.holdingsGuide = holdingsGuide;
    }

    public Warnings(String abstract_, boolean iswarning, SourceGuide sourceGuide){
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
        this.sourceGuide = sourceGuide;
    }

	public int getWarId() {
		return this.warId;
	}

	public void setWarId(int warId) {
		this.warId = warId;
	}

	public HoldingsGuide getHoldingsGuide() {
		return this.holdingsGuide;
	}

	public void setHoldingsGuide(HoldingsGuide holdingsGuide) {
		this.holdingsGuide = holdingsGuide;
	}

	public FindingAid getFindingAid() {
		return this.findingAid;
	}

	public void setFindingAid(FindingAid findingAid) {
		this.findingAid = findingAid;
	}

    public SourceGuide getSourceGuide() {
        return sourceGuide;
    }

    public void setSourceGuide(SourceGuide sourceGuide) {
        this.sourceGuide = sourceGuide;
    }

    public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	public Boolean getIswarning() {
		return this.iswarning;
	}

	public void setIswarning(Boolean iswarning) {
		this.iswarning = iswarning;
	}

}
