package eu.apenet.persistence.vo;
// Generated 15-oct-2010 13:00:40 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Warnings generated by hbm2java
 */
@Entity
@Table(name = "warnings")
public class Warnings implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 4346259413192033999L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int warId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hg_id", foreignKey = @ForeignKey(name = "warnings_hg_id_fkey"))
    private HoldingsGuide holdingsGuide;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fa_id", foreignKey = @ForeignKey(name = "warnings_fa_id_fkey"))
    private FindingAid findingAid;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sg_id", foreignKey = @ForeignKey(name = "warnings_sg_id_fkey"))
    private SourceGuide sourceGuide;
    @Column(name = "abstract")
    private String abstract_;
    private Boolean iswarning;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "eac_id", foreignKey = @ForeignKey(name = "warnings_eac_id_fkey"))
    private EacCpf eacCpf;

    public Warnings() {
    }

    public Warnings(int warId, String abstract_) {
        this.warId = warId;
        this.abstract_ = abstract_;
    }

    public Warnings(int warId, HoldingsGuide holdingsGuide,
            FindingAid findingAid, String abstract_, Boolean iswarning) {
        this.warId = warId;
        this.holdingsGuide = holdingsGuide;
        this.findingAid = findingAid;
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
    }

    public Warnings(String abstract_, boolean iswarning, FindingAid findingAid) {
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
        this.findingAid = findingAid;
    }

    public Warnings(String abstract_, boolean iswarning, HoldingsGuide holdingsGuide) {
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
        this.holdingsGuide = holdingsGuide;
    }

    public Warnings(String abstract_, boolean iswarning, SourceGuide sourceGuide) {
        this.abstract_ = abstract_;
        this.iswarning = iswarning;
        this.sourceGuide = sourceGuide;
    }

    public int getWarId() {
        return this.warId;
    }

    public void setWarId(int warId) {
        this.warId = warId;
    }

    public HoldingsGuide getHoldingsGuide() {
        return this.holdingsGuide;
    }

    public void setHoldingsGuide(HoldingsGuide holdingsGuide) {
        this.holdingsGuide = holdingsGuide;
    }

    public FindingAid getFindingAid() {
        return this.findingAid;
    }

    public void setFindingAid(FindingAid findingAid) {
        this.findingAid = findingAid;
    }

    public SourceGuide getSourceGuide() {
        return sourceGuide;
    }

    public void setSourceGuide(SourceGuide sourceGuide) {
        this.sourceGuide = sourceGuide;
    }

    public String getAbstract_() {
        return this.abstract_;
    }

    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }

    public Boolean getIswarning() {
        return this.iswarning;
    }

    public void setIswarning(Boolean iswarning) {
        this.iswarning = iswarning;
    }

    public Ead getEad() {
        if (findingAid != null) {
            return findingAid;
        } else if (holdingsGuide != null) {
            return holdingsGuide;
        } else {
            return sourceGuide;
        }
    }

    public void setEad(Ead ead) {
        if (ead == null) {
            findingAid = null;
            holdingsGuide = null;
            sourceGuide = null;
        } else {
            if (ead instanceof FindingAid) {
                findingAid = (FindingAid) ead;
            } else if (ead instanceof HoldingsGuide) {
                holdingsGuide = (HoldingsGuide) ead;
            } else if (ead instanceof SourceGuide) {
                sourceGuide = (SourceGuide) ead;
            }
        }
    }

    public EacCpf getEacCpf() {
        return eacCpf;
    }

    public void setEacCpf(EacCpf eacCpf) {
        this.eacCpf = eacCpf;
    }
}
