DELETE FROM ese_state;

INSERT INTO ese_state (id, state) VALUES (3, 'Removed');
INSERT INTO ese_state (id, state) VALUES (2, 'Published');
INSERT INTO ese_state (id, state) VALUES (1, 'Not published');

DELETE FROM cou_alternative_name;
DELETE FROM country;
DELETE FROM lang;

INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (4, 'GREEK', 'GRE', 'EL', 'Ελληνικά');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (10, 'LATVIAN', 'LAV', 'LV', 'Latviešu');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (1, 'SPANISH', 'SPA', 'ES', 'Español');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (2, 'FRENCH', 'FRE', 'FR', 'Français');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (3, 'GERMAN', 'GER', 'DE', 'Deutch');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (5, 'POLISH', 'POL', 'PL', 'Polsky');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (6, 'SWEDISH', 'SWE', 'SW', 'Svenska');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (7, 'DUTCH', 'DUT', 'NL', 'Nederlands');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (8, 'ENGLISH', 'ENG', 'EN', 'English');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (9, 'IRISH', 'GLE', 'GA', 'Gaeilge');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (11, 'MALTESE', 'MLT', 'MT', 'Malti');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (12, 'PORTUGUESE', 'POR', 'PT', 'Português');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (13, 'SLOVENIAN', 'SLV', 'SL', 'Slovenščina');
INSERT INTO lang (id, lname, isoname, iso2name, lnativename) VALUES (14, 'FINNISH', 'FIN', 'FI', 'Suomi');

INSERT INTO country (id, cname, isoname, al_order) VALUES (1, 'SPAIN', 'ES', 4);
INSERT INTO country (id, cname, isoname, al_order) VALUES (2, 'FRANCE', 'FR', 5);
INSERT INTO country (id, cname, isoname, al_order) VALUES (3, 'GERMANY', 'DE', 2);
INSERT INTO country (id, cname, isoname, al_order) VALUES (4, 'GREECE', 'GR', 6);
INSERT INTO country (id, cname, isoname, al_order) VALUES (5, 'POLAND', 'PL', 10);
INSERT INTO country (id, cname, isoname, al_order) VALUES (6, 'SWEDEN', 'SE', 14);
INSERT INTO country (id, cname, isoname, al_order) VALUES (7, 'NETHERLANDS', 'NL', 9);
INSERT INTO country (id, cname, isoname, al_order) VALUES (8, 'BELGIUM', 'BE', 1);
INSERT INTO country (id, cname, isoname, al_order) VALUES (9, 'SLOVENIA', 'SI', 12);
INSERT INTO country (id, cname, isoname, al_order) VALUES (10, 'IRELAND', 'IE', 3);
INSERT INTO country (id, cname, isoname, al_order) VALUES (11, 'LATVIA', 'LV', 7);
INSERT INTO country (id, cname, isoname, al_order) VALUES (12, 'MALTA', 'MT', 8);
INSERT INTO country (id, cname, isoname, al_order) VALUES (13, 'PORTUGAL', 'PT', 11);
INSERT INTO country (id, cname, isoname, al_order) VALUES (14, 'FINLAND', 'FI', 13);

INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (1, 'Spanien', 1, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (2, 'Frankreich', 2, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (3, 'Deutschland', 3, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (4, 'Griechenland', 4, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (5, 'Polen', 5, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (6, 'Schweden', 6, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (7, 'Niederlande', 7, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (8, 'Belgien', 8, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (9, 'Slowenien', 9, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (10, 'Irland', 10, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (11, 'Lettland', 11, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (12, 'Malta', 12, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (13, 'Portugal', 13, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (14, 'Finnland', 14, 3);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (15, 'Ισπανία', 1, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (16, 'Γαλλία', 2, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (17, 'Γερμανία', 3, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (18, 'Ελλάς', 4, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (19, 'Πολωνία', 5, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (20, 'Σουηδία', 6, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (21, 'Ολλανδία', 7, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (22, 'Βέλγιο', 8, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (23, 'Σλοβενία', 9, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (24, 'Ιρλανδίας', 10, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (25, 'Λεττονία', 11, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (26, 'Μάλτα', 12, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (27, 'Πορτογαλία', 13, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (28, 'Φινλανδία', 14, 4);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (29, 'Spain', 1, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (30, 'France', 2, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (31, 'Germany', 3, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (32, 'Greece', 4, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (33, 'Poland', 5, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (34, 'Sweden', 6, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (35, 'Netherlands', 7, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (36, 'Belgium', 8, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (37, 'Slovenia', 9, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (38, 'Ireland', 10, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (39, 'Latvia', 11, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (40, 'Malta', 12, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (41, 'Portugal', 13, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (42, 'Finland', 14, 8);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (43, 'España', 1, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (44, 'Francia', 2, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (45, 'Alemania', 3, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (46, 'Grecia', 4, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (47, 'Polonia', 5, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (48, 'Suecia', 6, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (49, 'Países Bajos', 7, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (50, 'Bélgica', 8, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (51, 'Eslovenia', 9, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (52, 'Irlanda', 10, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (53, 'Letonia', 11, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (54, 'Malta', 12, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (55, 'Portugal', 13, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (56, 'Finlandia', 14, 1);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (57, 'Espanja', 1, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (58, 'Ranska', 2, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (59, 'Saksa', 3, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (60, 'Kreikka', 4, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (61, 'Puola', 5, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (62, 'Ruotsi', 6, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (63, 'Alankomaat', 7, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (64, 'Belgia', 8, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (65, 'Slovenia', 9, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (66, 'Irlanti', 10, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (67, 'Latvia', 11, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (68, 'Malta', 12, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (69, 'Portugali', 13, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (70, 'Suomi', 14, 14);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (71, 'Espagne', 1, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (72, 'France', 2, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (73, 'Allemagne', 3, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (74, 'Grèce', 4, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (75, 'Pologne', 5, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (76, 'Suède', 6, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (77, 'Pays-Bas', 7, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (78, 'Belgique', 8, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (79, 'Slovénie', 9, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (80, 'Irlande', 10, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (81, 'Lettonie', 11, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (82, 'Malta', 12, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (83, 'Portugal', 13, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (84, 'Finlande', 14, 2);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (85, 'An Spáinn', 1, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (86, 'An Fhrainc', 2, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (87, 'An Ghearmáin', 3, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (88, 'An Ghréig', 4, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (89, 'An Pholainn', 5, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (90, 'An tSualainn', 6, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (91, 'An Ísiltír', 7, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (92, 'An Bheilg', 8, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (93, 'An tSlóivéin', 9, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (94, 'Éire', 10, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (95, 'An Laitvia', 11, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (96, 'Málta', 12, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (97, 'An Phortaingéil', 13, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (98, 'An Fhionlainn', 14, 9);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (99, 'Spānija', 1, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (100, 'Francija', 2, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (101, 'Vācija', 3, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (102, 'Grieķija', 4, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (103, 'Polija', 5, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (104, 'Zviedrija', 6, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (105, 'Nīderlande', 7, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (106, 'Beļģija', 8, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (107, 'Slovēnija', 9, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (108, 'Īrija', 10, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (109, 'Latvija', 11, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (110, 'Malta', 12, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (111, 'Portugāle', 13, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (112, 'Somija', 14, 10);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (113, 'Spanja', 1, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (114, 'Franza', 2, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (115, 'Ġermanja', 3, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (116, 'Greċja', 4, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (117, 'Polonja', 5, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (118, 'Żvezja', 6, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (119, 'Olanda', 7, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (120, 'Belġju', 8, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (121, 'Slovenja', 9, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (122, 'Irlanda', 10, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (123, 'Latvja', 11, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (124, 'Malta', 12, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (125, 'Portugall', 13, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (126, 'Finlandja', 14, 11);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (127, 'Spanje', 1, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (128, 'Frankrijk', 2, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (129, 'Duitsland', 3, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (130, 'Griekenland', 4, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (131, 'Polen', 5, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (132, 'Zweden', 6, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (133, 'Nederland', 7, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (134, 'België', 8, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (135, 'Slovenië', 9, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (136, 'Ierland', 10, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (137, 'Letland', 11, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (138, 'Malta', 12, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (139, 'Portugal', 13, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (140, 'Finland', 14, 7);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (141, 'Hiszpania', 1, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (142, 'Francja', 2, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (143, 'Niemcy', 3, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (144, 'Grecja', 4, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (145, 'Polska', 5, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (146, 'Szwecja', 6, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (147, 'Holandia', 7, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (148, 'Belgia', 8, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (149, 'Słowenia', 9, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (150, 'Irlandia', 10, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (151, 'Łotwa', 11, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (152, 'Malta', 12, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (153, 'Portugalia', 13, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (154, 'Finlandia', 14, 5);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (155, 'Espanha', 1, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (156, 'França', 2, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (157, 'Alemanha', 3, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (158, 'Grécia', 4, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (159, 'Polónia', 5, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (160, 'Suécia', 6, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (161, 'Países Baixos', 7, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (162, 'Bélgica', 8, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (163, 'Eslovénia', 9, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (164, 'Irlanda', 10, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (165, 'Letónia', 11, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (166, 'Malta', 12, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (167, 'Portugal', 13, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (168, 'Finlândia', 14, 12);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (169, 'Španija', 1, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (170, 'Francija', 2, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (171, 'Nemčija', 3, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (172, 'Grčija', 4, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (173, 'Poljska', 5, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (174, 'Švedska', 6, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (175, 'Nizozemska', 7, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (176, 'Belgija', 8, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (177, 'Slovenija', 9, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (178, 'Irska', 10, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (179, 'Latvija', 11, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (180, 'Malta', 12, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (181, 'Portugalska', 13, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (182, 'Finska', 14, 13);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (183, 'Spanien', 1, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (184, 'Frankrike', 2, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (185, 'Tyskland', 3, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (186, 'Grekland', 4, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (187, 'Polen', 5, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (188, 'Sverige', 6, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (189, 'Nederländerna', 7, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (190, 'Belgien', 8, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (191, 'Slovenien', 9, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (192, 'Irland', 10, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (193, 'Lettland', 11, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (194, 'Malta', 12, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (195, 'Portugal', 13, 6);
INSERT INTO cou_alternative_name (id, cou_an_name, cou_id, lng_id) VALUES (196, 'Finland', 14, 6);

DELETE FROM upload_method;

INSERT INTO upload_method (id, method) VALUES (1, 'OAI-PMH');
INSERT INTO upload_method (id, method) VALUES (2, 'FTP');
INSERT INTO upload_method (id, method) VALUES (3, 'HTTP');

DELETE FROM user_role;

INSERT INTO user_role (id, role) VALUES (1, 'countryManager');
INSERT INTO user_role (id, role) VALUES (2, 'institutionManager');
INSERT INTO user_role (id, role) VALUES (3, 'admin');
INSERT INTO user_role (id, role) VALUES (8, 'countryManagerCoordinator');