ALTER TABLE topic ALTER COLUMN property_key TYPE varchar(40);
UPDATE topic SET property_key='german.democratic.republic', description='German Democratic Republic' WHERE property_key='gdr';
UPDATE topic SET property_key='economics', description='Economics' WHERE property_key='econimics';
UPDATE topic SET property_key='national.administration', description='National administration' WHERE property_key='national.admin';

INSERT INTO topic(property_key, description,position) VALUES ('agriculture', 'Agriculture',17);
INSERT INTO topic(property_key, description,position) VALUES ('architecture', 'Architecture',18);
INSERT INTO topic(property_key, description,position) VALUES ('armed.forces', 'Armed forces',19);
INSERT INTO topic(property_key, description,position) VALUES ('arts', 'Arts',20);
INSERT INTO topic(property_key, description,position) VALUES ('battles', 'Battles',21);
INSERT INTO topic(property_key, description,position) VALUES ('buildings', 'Buildings',22);
INSERT INTO topic(property_key, description,position) VALUES ('catholicism', 'Catholicism',23);
INSERT INTO topic(property_key, description,position) VALUES ('charity', 'Charity',24);
INSERT INTO topic(property_key, description,position) VALUES ('charters', 'Charters',25);
INSERT INTO topic(property_key, description,position) VALUES ('church.records.and.registers', 'Church records and registers',26);
INSERT INTO topic(property_key, description,position) VALUES ('civil.wars.events', 'Civil wars (events)',27);
INSERT INTO topic(property_key, description,position) VALUES ('classical.period', 'Classical period',28);
INSERT INTO topic(property_key, description,position) VALUES ('colonialism', 'Colonialism',29);
INSERT INTO topic(property_key, description,position) VALUES ('communism', 'Communism',30);
INSERT INTO topic(property_key, description,position) VALUES ('concentration.camp', 'Concentration camp',31);
INSERT INTO topic(property_key, description,position) VALUES ('crusades', 'Crusades',32);
INSERT INTO topic(property_key, description,position) VALUES ('culture', 'Culture',33);
INSERT INTO topic(property_key, description,position) VALUES ('early.modern.period', 'Early modern period',34);
INSERT INTO topic(property_key, description,position) VALUES ('education', 'Education',35);
INSERT INTO topic(property_key, description,position) VALUES ('european.administration', 'European administration',36);
INSERT INTO topic(property_key, description,position) VALUES ('european.cooperation', 'European cooperation',37);
INSERT INTO topic(property_key, description,position) VALUES ('european.court.of.justice', 'European Court of Justice',38);
INSERT INTO topic(property_key, description,position) VALUES ('european.economic.cooperation', 'European economic cooperation',39);
INSERT INTO topic(property_key, description,position) VALUES ('european.industrial.cooperation', 'European industrial cooperation',40);
INSERT INTO topic(property_key, description,position) VALUES ('european.institutions', 'European institutions',41);
INSERT INTO topic(property_key, description,position) VALUES ('european.legal.instruments', 'European legal instruments',42);
INSERT INTO topic(property_key, description,position) VALUES ('european.parliament', 'European Parliament',43);
INSERT INTO topic(property_key, description,position) VALUES ('european.union', 'European Union',44);
INSERT INTO topic(property_key, description,position) VALUES ('french.revolution', 'French Revolution (1789-1799)',45);
INSERT INTO topic(property_key, description,position) VALUES ('french.revolutionary.wars', 'French Revolutionary Wars (1792-1800)',46);
INSERT INTO topic(property_key, description,position) VALUES ('genealogy.archives', 'Genealogy archives',47);
INSERT INTO topic(property_key, description,position) VALUES ('health', 'Health',48);
INSERT INTO topic(property_key, description,position) VALUES ('heresy', 'Heresy',49);
INSERT INTO topic(property_key, description,position) VALUES ('industrialisation', 'Industrialisation',50);
INSERT INTO topic(property_key, description,position) VALUES ('justice', 'Justice',51);
INSERT INTO topic(property_key, description,position) VALUES ('lifestyle', 'Lifestyle',52);
INSERT INTO topic(property_key, description,position) VALUES ('maps', 'Maps',53);
INSERT INTO topic(property_key, description,position) VALUES ('medical.sciences', 'Medical sciences',54);
INSERT INTO topic(property_key, description,position) VALUES ('monasteries', 'Monasteries',55);
INSERT INTO topic(property_key, description,position) VALUES ('municipal.government', 'Municipal government',56);
INSERT INTO topic(property_key, description,position) VALUES ('music', 'Music',57);
INSERT INTO topic(property_key, description,position) VALUES ('french.napoleon.i', 'Napoléon I, Emperor of the French, 1769-1821',58);
INSERT INTO topic(property_key, description,position) VALUES ('french.napoleon.iii', 'Napoléon III, Emperor of the French, 1808-1873',59);
INSERT INTO topic(property_key, description,position) VALUES ('napoleonic.wars', 'Napoleonic Wars (1800-1815)',60);
INSERT INTO topic(property_key, description,position) VALUES ('notaries', 'Notaries',61);
INSERT INTO topic(property_key, description,position) VALUES ('photography', 'Photography',62);
INSERT INTO topic(property_key, description,position) VALUES ('population.cencuses', 'Population cencuses',63);
INSERT INTO topic(property_key, description,position) VALUES ('poverty', 'Poverty',64);
INSERT INTO topic(property_key, description,position) VALUES ('protestantism', 'Protestantism',65);
INSERT INTO topic(property_key, description,position) VALUES ('rebellions', 'Rebellions',66);
INSERT INTO topic(property_key, description,position) VALUES ('religion', 'Religion',67);
INSERT INTO topic(property_key, description,position) VALUES ('renaissance', 'Renaissance',68);
INSERT INTO topic(property_key, description,position) VALUES ('revolutions', 'Revolutions',69);
INSERT INTO topic(property_key, description,position) VALUES ('revolutions.of.1848', 'Revolutions of 1848',70);
INSERT INTO topic(property_key, description,position) VALUES ('romanticism', 'Romanticism',71);
INSERT INTO topic(property_key, description,position) VALUES ('royalty', 'Royalty',72);
INSERT INTO topic(property_key, description,position) VALUES ('schools', 'Schools',73);
INSERT INTO topic(property_key, description,position) VALUES ('science', 'Science',74);
INSERT INTO topic(property_key, description,position) VALUES ('social.history', 'Social history',75);
INSERT INTO topic(property_key, description,position) VALUES ('socialism', 'Socialism',76);
INSERT INTO topic(property_key, description,position) VALUES ('statistics', 'Statistics',77);
INSERT INTO topic(property_key, description,position) VALUES ('thirty.year.war', 'Thirty Year War',78);
INSERT INTO topic(property_key, description,position) VALUES ('trade.unions', 'Trade unions',79);
INSERT INTO topic(property_key, description,position) VALUES ('universities', 'Universities',80);
INSERT INTO topic(property_key, description,position) VALUES ('wars.events', 'Wars (events)',81);
INSERT INTO topic(property_key, description,position) VALUES ('women', 'Women',82);
INSERT INTO topic(property_key, description,position) VALUES ('germany.sed.fdgb', 'SED/FDGB',83);