ALTER TABLE topic_mapping ALTER COLUMN ai_id DROP NOT NULL;
ALTER TABLE topic_mapping ADD COLUMN country_id INTEGER;
ALTER TABLE topic_mapping ADD CONSTRAINT country_id_fkey FOREIGN KEY (country_id) REFERENCES country(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
