DELETE FROM rights_information;

INSERT INTO rights_information VALUES (1, 'PDM', 'http://creativecommons.org/publicdomain/mark/1.0/', 'This object is not or no longer protected by copyright and has been labelled with the Public Domain Mark. It can be used by anyone without any restrictions.', 'Public Domain Mark');
INSERT INTO rights_information VALUES (2, 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/', 'This object is made available under the Creative Commons CC0 1.0 Public Domain Dedication. All possible existing rights in the content are waived, and the object can be used by anyone without any restrictions.', 'Creative Commons CC0 Public Domain Dedication');
INSERT INTO rights_information VALUES (3, 'CC BY', 'http://creativecommons.org/licenses/by/4.0/', 'This object is made available under the terms of the Creative Commons - Attribution (BY) licence. You can copy, redistribute, remix, tweak, and build upon the licensed object, even commercially, as long as you attribute the rights holder as described in the licence.', 'Creative Commons Attribution');
INSERT INTO rights_information VALUES (4, 'CC BY-SA', 'http://creativecommons.org/licenses/by-sa/4.0/', 'This object is made available under the terms of the Creative Commons - Attribution, ShareAlike (BY-SA) licence. You can copy, redistribute, remix, tweak and build upon the licensed object, even for commercial purposes, as long as you attribute the rights holder as described in the licence, and you license your adaptations of the object under the same terms.', 'Creative Commons Attribution, ShareAlike');
INSERT INTO rights_information VALUES (5, 'CC BY-ND', 'http://creativecommons.org/licenses/by-nd/4.0/', 'This object is made available under the terms of the Creative Commons - Attribution, No Derivates (BY-ND) licence. You can copy and redistribute the object, even commercially, as long as no alteration is made to the object and you attribute the rights holder as described in the licence. If you remix, transform or build upon the object, you may not distribute the modified material.', 'Creative Commons Attribution, No Derivatives');
INSERT INTO rights_information VALUES (6, 'CC BY-NC', 'http://creativecommons.org/licenses/by-nc/4.0/', 'This object is made available under the terms of the Creative Commons - Attribution, Non-Commercial (BY-NC) licence. You can copy, redistribute, remix, tweak, and build upon the licensed object for non-commercial use only and as long as you attribute the rights holder as described in the licence.', 'Creative Commons Attribution, Non-Commercial');
INSERT INTO rights_information VALUES (7, 'CC BY-NC-SA', 'http://creativecommons.org/licenses/by-nc-sa/4.0/', 'This object is made available under the terms of the Creative Commons - Attribution, Non-Commercial, ShareAlike (BY-NC-SA) licence. You can copy, redistribute, remix, tweak, and build upon the licensed object for non-commercial use only, as long as you attribute the rights holder as described in the licence, and as long as you license your adaptations of the object under the same terms.', 'Creative Commons Attribution, Non-Commercial, ShareAlike');
INSERT INTO rights_information VALUES (8, 'CC BY-NC-ND', 'http://creativecommons.org/licenses/by-nc-nd/4.0/', 'This object is made available under the terms of the Creative Commons - Attribution, Non-Commercial, No Derivates (BY-NC-ND) licence. You can copy and redistribute the object for non-commercial use only, as long as no alteration is made to the object and as long as you attribute the rights holder as described in the licence. If you remix, transform or build upon the object, you may not distribute the modified material.', 'Creative Commons Attribution, Non-Commercial, No Derivatives');
INSERT INTO rights_information VALUES (9, 'NoC-NC', 'http://rightsstatements.org/vocab/NoC-NC/1.0/', 'This object is in the public domain, but has been digitised as the outcome of a public-private partnership, where the terms of the contractual agreement limit commercial use for a certain period of time. You can copy, redistribute, remix, tweak, and build upon the object for non-commercial use only.', 'No Copyright, Non-Commercial Use Only');
INSERT INTO rights_information VALUES (10, 'InC-EU-OW', 'http://rightsstatements.org/vocab/InC-OW-EU/1.0/', 'This object has been identified as an Orphan Work in the country of first publication and in line with the requirements of the national law implementing Directive 2012/28/EU of the European Parliament and of the Council of 25 October 2012 on certain permitted uses of orphan works. You are free to use this object in any way that is permitted by the copyright and related rights legislation that applies to your use. Please note that you are responsible for your own use, including the need to obtain other permissions e.g. with regard to publicity, privacy or moral rights.', 'In Copyright, Orphan Work');
INSERT INTO rights_information VALUES (11, 'NoC-OKLR', 'http://rightsstatements.org/vocab/NoC-OKLR/1.0/', 'This object is in the public domain, but is subject to known legal restrictions other than copyright which prevent its free re-use. Please contact the providing institution for more information.', 'In Copyright, Other Known Legal Restrictions');
INSERT INTO rights_information VALUES (12, 'InC', 'http://rightsstatements.org/vocab/InC/1.0/', 'This object is currently in copyright. Please contact the providing institution for more information and in order to acquire additional permissions for re-use.', 'In Copyright');
INSERT INTO rights_information VALUES (13, 'CNE', 'http://rightsstatements.org/vocab/CNE/1.0/', 'The copyright status of this object has not been evaluated yet. Please contact the providing institution for more information. You are free to use this object in any way that is permitted by the copyright and related rights legislation that applies to your use. Please note that you are responsible for your own use, including the need to obtain other permissions e.g. with regard to publicity, privacy, or moral rights.', 'Copyright Not Evaluated');
INSERT INTO rights_information VALUES (14, 'InC-EDU', 'http://rightsstatements.org/vocab/InC-EDU/1.0/', 'This object is currently in copyright and the rights holder(s) have allowed re-use for educational purposes only. You are free to use this object in any way that is permitted by the copyright and related rights legislation that applies to your use. Please note that you are responsible for your own use, including the need to obtain other permissions e.g. with regard to publicity, privacy or moral rights. Please contact the providing institution for more information and in order to acquire additional permissions for any other uses.', 'In Copyright, Education Use Permitted');
